### ISSUE TITLE
Need info about message selector usage for Java Test Designer

### ISSUE THREAD

**Issue by olha-bastieieva** [citrusframework/citrus-samples#14]
It would be really great to have info about message selector usage for Java Test Designer with correct xpath value format (please refer to the question at http://stackoverflow.com/questions/41878355/citrus-framework-need-example-of-correct-usage-of-message-selector-for-java-tes?s=1|0.0000)

**Comment by svettwer** [comment]
Hi!

I'll close this issue as the answer has been provided via [stackoverflow](https://stackoverflow.com/questions/41878355/citrus-framework-need-example-of-correct-usage-of-message-selector-for-java-tes).

In addition, you can find a [general introduction into message selectors](http://citrusframework.org/citrus/reference/html/index.html#message-selectors) in the documentation as well as for [xpath message selectors](http://citrusframework.org/citrus/reference/html/index.html#xpath-message-selector) and [json path message selectors](http://citrusframework.org/citrus/reference/html/index.html#json-path-message-selector).

BR,
Sven
