### ISSUE TITLE
No example for procedure call using callable statement

### ISSUE THREAD

**Issue by vmasule** [citrusframework/citrus-samples#28]
Current callable example use JdbcServer and I got a requirement of connecting to Database and execute stored procedure but I don't know how that can be done without JdbcServer as I just need Datasource to do it.

Please point me if you have any example completely based on `DataSource` rather than `JdbcServer` which is what I have seen in your examples

**Comment by svettwer** [comment]
Hi!

Sorry for the late response. 
It's possible to send any kind of statement to a database using data sources with Citrus.

```java
query(todoDataSource)
  .statement("select count(*) as cnt from todo_entries where title = '${todoName}'")
  .validate("cnt", "0");
```
You'd just have to alter the statement and the validation part as required by your use case. The Citrus-JDBC-Server is not mandatory for this.

If you'd like to replace your productive or test database with a simulation that behaves just as your database would do, you should use the Citrus-JDBC-Server. In other words: If you use the Citrus-JDBC-Server you'd just specify the database content in a declarative way without setup or tear down procedure to prepare/clean-up the database before/after testing.

BR,
Sven

**Comment by svettwer** [comment]
Closed due to inactivity
