### ISSUE TITLE
2.8.0-SNAPSHOT

### ISSUE THREAD

**Issue by shenora** [citrusframework/citrus-samples#31]
Seems like the 2.8.0-SNAPSHOT samples are not present in the repository.Can you please add them?

**Comment by bahadurbaniya** [comment]
[ERROR] Failed to execute goal on project citrus-xml-sample-mail: Could not resolve dependencies for project com.consol.citrus.samples:citrus-xml-sample-mail:jar:2.8.0-SNAPSHOT: The following artifacts could not be resolved: com.consol.citrus:citrus-http:jar:2.8.0-SNAPSHOT, com.consol.citrus:citrus-mail:
jar:2.8.0-SNAPSHOT: Could not find artifact com.consol.citrus:citrus-http:jar:2.8.0-SNAPSHOT in consol-labs-snapshots (http://labs.consol.de/maven/snapshots-repository/) -> [Help 1]

missing 2.8.0-SNAPSHOT  in https://labs.consol.de/maven/snapshots-repository/com/consol/citrus/citrus-http/

**Comment by shenora** [comment]
Yes, I am getting the same error. Can this be resolved?

**Comment by svettwer** [comment]
Hi!

Sure, we'll have a look at this. Thx for the details @bahadurbaniya.

BR, 
Sven

**Comment by svettwer** [comment]
Hi!

I just cleared my local repository and executed the tests. It should work now.

BR,
Sven
