### ISSUE TITLE
Issues while Mock SOAP response - Static response adapter

### ISSUE THREAD

**Issue by thangatina1** [citrusframework/citrus-samples#36]
Issues : I am following the sample in the Soap-static-response, to mock on of my service response.  I am trying to mock the response form a IBM BPM server on port 9080. I have the same port for the client and server as in the example. I am unable to run my test. I find the same error when i run the sample test too. I am running the test on Win 7 machine.

Error:
icApplicationContext| Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'wpsServer' defined in class path resource [com/consol/citrus/samples/bpm/MockConfig.class]: Invocation of init method failed; nested exception is com.consol.citrus.exceptions.CitrusRuntimeException: java.net.BindException: **Address already in use: bind**
15:45:53,332 ERROR t.TestContextManager| Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@5bd03f44] to prepare test instance [com.liberty.grm.products.citrus.integrationTest.MockTestIT@76508ed1]
java.lang.IllegalStateException: **Failed to load ApplicationContext**

 Config file : 
------------------------

@Configuration
public class MockConfig {

	@Bean
	public SoapMessageFactory messageFactory() {
		return new SaajSoapMessageFactory();
	}
	
	@Bean
	public WebServiceServer wpsServer() throws Exception {
	    return CitrusEndpoints.soap()
	            .server()
	            .port(9080)
	            .endpointAdapter(dispatchingEndpointAdapter())
	            .timeout(10000)
	            .autoStart(true)
	            .build();
	}

	@Bean
	public WebServiceClient customerInformationMarketService() {
		return CitrusEndpoints.soap().client()
				.defaultUri("http://localhost:9080/domain/cccc/cccc/sca/zzzzzzzzServiceWS")
				.build();
	}

	@Bean
	public RequestDispatchingEndpointAdapter dispatchingEndpointAdapter() {
	    RequestDispatchingEndpointAdapter dispatchingEndpointAdapter = new RequestDispatchingEndpointAdapter();
	    dispatchingEndpointAdapter.setMappingKeyExtractor(mappingKeyExtractor());
	    dispatchingEndpointAdapter.setMappingStrategy(mappingStrategy());
	    return dispatchingEndpointAdapter;
	}
	
	@Bean
	public HeaderMappingKeyExtractor mappingKeyExtractor() {
	    return new SoapActionMappingKeyExtractor();
	}
	

	
	@Bean
	public SimpleMappingStrategy mappingStrategy() {
	    SimpleMappingStrategy mappingStrategy = new SimpleMappingStrategy();

	    Map<String, EndpointAdapter> mappings = new HashMap<>();

	    mappings.put("getInsScore", getInsScoreResponseAdapter());
	    mappingStrategy.setAdapterMappings(mappings);
	    return mappingStrategy;
	}
	
	@Bean
	public EndpointAdapter getInsScoreResponseAdapter() {
	    StaticResponseEndpointAdapter endpointAdapter = new StaticResponseEndpointAdapter();
	    endpointAdapter.setMessagePayload("<se:determineInsuranceScoreResponse\r\n" + 
				"	xmlns:se=\"http://pi.lmig.com/customerInformationMarketService\">" 
				+ "<response>"
				+ "<ID>-9.99999999734E11</ID>" 
				+ "<TrackingInformation>"
				+ "<ClientCorrelationID>123456789</ClientCorrelationID>"
				+ "<ServerAssignedID>b39f1275-99f2-4a5c-9bfc-10ac3d46b035" 
				+ "</ServerAssignedID>"
				+ "</TrackingInformation>"
				+ "<VersionInformation>"
				+ "<Description>CUSDBSPSV_2014_02_B1_TEST 11/21/2013 09:25AM and"
				+ "SHAREDPSV_2011_11_DEFAULT_B1</Description>" 
				+ "<Major>1</Major>" 
				+ "<Minor>0</Minor>"
				+ "</VersionInformation>" 
				+ "<IsSuccess>true</IsSuccess>" 
				+ "<InsuranceScore>"
				+ "<RequestStatusCode>NE</RequestStatusCode>" 
				+ "</InsuranceScore>" 
				+ "</response>"
				+ "</se:determineInsuranceScoreResponse");
	    return endpointAdapter;
	}
}

************************************************************************************************

Test file : 
---------------
	@Autowired
	private WebServiceClient customerInformationMarketService;

	@Test
	@CitrusTest
	public void testTodo() {
		soap()
		.client(customerInformationMarketService)
		.send()
		.soapAction("myAction")
		.payload(new ClassPathResource("templates/myRequest.xml"));

		soap()
		.client(customerInformationMarketService)
		.receive()
				.payload("<se:determineInsuranceScoreResponse\r\n" + 
						"	xmlns:se=\"http://pi.lmig.com/customerInformationMarketService\">" 
						+ "<response>"
						+ "<ID>-9.99999999734E11</ID>" 
						+ "<TrackingInformation>"
						+ "<ClientCorrelationID>123456789</ClientCorrelationID>"
						+ "<ServerAssignedID>b39f1275-99f2-4a5c-9bfc-10ac3d46b035" 
						+ "</ServerAssignedID>"
						+ "</TrackingInformation>"
						+ "<VersionInformation>"
						+ "<Description>CUSDBSPSV_2014_02_B1_TEST 11/21/2013 09:25AM and"
						+ "SHAREDPSV_2011_11_DEFAULT_B1</Description>" 
						+ "<Major>1</Major>" 
						+ "<Minor>0</Minor>"
						+ "</VersionInformation>" 
						+ "<IsSuccess>true</IsSuccess>" 
						+ "<InsuranceScore>"
						+ "<RequestStatusCode>NE</RequestStatusCode>" 
						+ "</InsuranceScore>" 
						+ "</response>"
						+ "</se:determineInsuranceScoreResponse");
	}
}

**Comment by svettwer** [comment]
Hi!

This message occurs, when a application is already running on this port. Please ensure that the port is free before you run the test, so that the soap server can startup.

Concerning the samples:
Depending on the machine you're using, it may be the case that your ports are still registered when running multiple samples in one maven process. The reason for that is, that the sample todo-app is started and stopped again and again for every sample.

BR,
Sven

**Comment by svettwer** [comment]
Hi!

You're welcome. It depends on what you would like to test.
Is it the IBM BPM server you want to test? In this case, I'd assume that the IBM BPM provides a soap server. If this is true, you would rather need a SOAP client than a server.

If you want to test how the IBM BPM server talks to another SOAP server of a third party provider, you'd have to deploy the simulated third party server on a different port.

If you just want to play around and see how citrus could simulate your IBM BPM, then yes, you'd have to make sure that the IBM BPM is stopped or the ports are reconfigured on server and client side.

BR,
Sven

**Comment by thangatina1** [comment]
Thank you
