### ISSUE TITLE
Unable to get the static SOAP Response

### ISSUE THREAD

**Issue by thangatina1** [citrusframework/citrus-samples#37]
Issue: 
I have my client at 9080 and my server at 9090.  all my beans get initialized correctly, but my SOAP response is received at the same port as my request. Please help me correct my mistake. I need to hit a WS and receive a static response for it, and assert them. 

**Error:**
********
**15:35:30,770 INFO  ent.WebServiceClient| SOAP message was sent to endpoint: 'http://localhost:9080/domain/customer/business/sca/xxxxxxWS'
15:35:30,770 INFO  ent.WebServiceClient| Received SOAP response on endpoint: 'http://localhost:9080/domain/customer/business/sca/xxxxxWS'**

15:42:11,444 DEBUG ltCorrelationManager| Saving correlated object for 'citrus_message_id = 'b3ed7860-580b-45fd-b48d-45ce99d60295''
15:42:11,444 INFO  port.LoggingReporter| 
15:42:11,444 DEBUG port.LoggingReporter| TEST STEP 1/2 SUCCESS
15:42:11,444 INFO  port.LoggingReporter| 
15:42:11,444 DEBUG port.LoggingReporter| TEST STEP 2/2: send
15:42:11,444 INFO  port.LoggingReporter| 
15:42:11,444 ERROR port.LoggingReporter| TEST FAILED MockTestIT.testDetermineInsuranceScoreMock <com.liberty.grm.products.citrus.integrationTest> Nested exception is: 
com.consol.citrus.exceptions.CitrusRuntimeException: Unable to create endpoint for static endpoint adapter type 'class com.consol.citrus.endpoint.adapter.RequestDispatchingEndpointAdapter'

**My Test File:**
*********************
public class MockTestIT extends TestNGCitrusTestDesigner {

	@Autowired
	private WebServiceClient customerInformationMarketService;
	
	@Autowired
	private WebServiceServer mockServer;

	@Test
	@CitrusTest
	public void testDetermineInsuranceScoreMock() {		
		
		soap()
		.client(customerInformationMarketService)
		.send()
		.soapAction("determineInsuranceScore")
		.payload(new ClassPathResource("templates/zzz.xml"));
		
		
	soap()
		.server(mockServer)
		.send()
		.xpath("//IsSuccess", "true")
		.xpath("//RequestStatusCode", "AA");
}
}

-----------------------------------------------------------------------------------------------
**My Config file**
************************

@Configuration
public class MockConfig {

	@Bean
	public SoapMessageFactory messageFactory() {
		return new SaajSoapMessageFactory();
	}
	

	@Bean
	public WebServiceClient customerInformationMarketService() {
		return CitrusEndpoints.soap().client()
				.defaultUri("http://localhost:9080/domain/customer/business/sca/xxxxWS")
			
				.build();
	}
	
	@Bean
	public WebServiceServer wpsServer() throws Exception {
		return CitrusEndpoints.soap()
	            .server()
	            .port(9090)
	            .endpointAdapter(dispatchingEndpointAdapter())
	            .timeout(10000)
	            .autoStart(true)
	            .build();
	}

	@Bean
	public RequestDispatchingEndpointAdapter dispatchingEndpointAdapter() {
	    RequestDispatchingEndpointAdapter dispatchingEndpointAdapter = new RequestDispatchingEndpointAdapter();
	    dispatchingEndpointAdapter.setMappingKeyExtractor(mappingKeyExtractor());
	    dispatchingEndpointAdapter.setMappingStrategy(mappingStrategy());
	    return dispatchingEndpointAdapter;
	}
	
	@Bean
	public HeaderMappingKeyExtractor mappingKeyExtractor() {
	    return new SoapActionMappingKeyExtractor();
	}
	

	@Bean
	public SimpleMappingStrategy mappingStrategy() {
	    SimpleMappingStrategy mappingStrategy = new SimpleMappingStrategy();

	    Map<String, EndpointAdapter> mappings = new HashMap<>();

	    mappings.put("determineInsuranceScore", determineInsuranceScoreResponseAdapter());
	    
	    mappingStrategy.setAdapterMappings(mappings);
	    return mappingStrategy;
	}
	
	@Bean
	public EndpointAdapter determineInsuranceScoreResponseAdapter() {
	    StaticResponseEndpointAdapter endpointAdapter = new StaticResponseEndpointAdapter();
	    endpointAdapter.setMessagePayload("<se:determineInsuranceScoreResponse\r\n" + 
				"	xmlns:se=\"http://pi.lmig.com/customerInformationMarketService\">" 
				+ "<response>"
				+ "<ID>-9.99999999734E11</ID>" 
				+ "<TrackingInformation>"
				+ "<ClientCorrelationID>123456789</ClientCorrelationID>"
				+ "<ServerAssignedID>b39f1275-99f2-4a5c-9bfc-10ac3d46b035" 
				+ "</ServerAssignedID>"
				+ "</TrackingInformation>"
				+ "<VersionInformation>"
				+ "<Description>CUSDBSPSV_2014_02_B1_TEST 11/21/2013 09:25AM and"
				+ "SHAREDPSV_2011_11_DEFAULT_B1</Description>" 
				+ "<Major>1</Major>" 
				+ "<Minor>0</Minor>"
				+ "</VersionInformation>" 
				+ "<IsSuccess>true</IsSuccess>" 
				+ "<InsuranceScore>"
				**+ "<RequestStatusCode>AA</RequestStatusCode>"** 
				+ "</InsuranceScore>" 
				+ "</response>"
				+ "</se:determineInsuranceScoreResponse");
	    return endpointAdapter;
	}   

}

---------------------------------------------------------

**Comment by svettwer** [comment]
Hi!

Well, you're starting a server at port `9090` and your requests are sent to port `9080`.
So your client will never reach your server, because it is requesting the wrong port. 
`http://localhost:9090/` as a client url would be the way to go.

BR,
Sven

**Comment by thangatina1** [comment]
@svettwer : Thanks for your support.
