### ISSUE TITLE
Question regrading reporting in Citrus

### ISSUE THREAD

**Issue by mmarciniuk** [citrusframework/citrus-samples#45]
**Citrus Version**
2.8.0

**Question**
Let's say that I have a custom report class:
```java
public class MyCustomTestReporter extends AbstractTestReporter implements TestSuiteListener, TestListener, TestActionListener, MessageListener, TestReporter {
...
}
```

and my test class looks something like this:
```java
public class MyTestIT extends TestNGCitrusTestRunner {
private TestData testData;

public TestData getTestData() {
		return testData;
	}

...
}
```
Can I somehow access to `testData` (for eg. using `getTestData()`) from `MyCustomTestReporter`?

**What I've tried so far**
I tried to use `test (type: TestCase)` from the method `public void onTestStart(TestCase test)`.
Unfortunately, I couldn't access this variable.

Can you please advise?

**Additional information**

**Comment by mmarciniuk** [comment]
Nvm, I found the solution.

**Comment by svettwer** [comment]
Hi,

sorry, I did not find any time to take a look at your issue. Would it be possible for you to share your solution so that other users with the same problem find some help here?

Thx and BR, 
Sven

**Comment by mmarciniuk** [comment]
Hi @svettwer,

Of course, my solution looks as follows:

In my class _MyCustomTestReporter_, I've created the variable NAME_OF_VARIABLE_FOR_TEST_CASE.

```
public class MyCustomTestReporter extends AbstractTestReporter implements TestSuiteListener, TestListener, TestActionListener, MessageListener, TestReporter {
public static final String NAME_OF_VARIABLE_FOR_TEST_CASE = "testCase";
...
}
```

Then in my test, I have a method _executePrerequisites_ which is always called before every test.
In this method, I'm adding variable _testData_.
Example:
```
protected void executePrerequisites(TestContext 
variable(MyCustomTestReporter.NAME_OF_VARIABLE_FOR_TEST_CASE, this.testData.getName()); // of course I can add this variable(MyCustomTestReporter.NAME_OF_VARIABLE_FOR_TEST_CASE, this.testData) and then in report I will need to cast this variale to appropriet class
...
}
```

Example of the test method:
@CitrusTest
@Parameters("context")
@Test
public void someTest(@Optional @CitrusResource TestContext citrusTestContext) {
this.executePrerequisites(citrusTestContext);
...
}

Thanks to this approach in method _onTestFinish_ I can retrieve test data.
```
@Override
public void onTestFinish(TestCase test) {
String testCaseName = String.valueOf(test.getVariableDefinitions().get(NAME_OF_VARIABLE_FOR_TEST_CASE));
		if (testCaseName != null) {
			this.currentTestCase.getModel().setName(testCaseName);
		}
}
```

I'm retrieving this variable in _onTestFinish_ because when the method _onTestStart_ is called this variable is not initialized yet.

Mariusz

**Comment by svettwer** [comment]
Hi @mmarciniuk!

Thx for sharing your attempt. :+1:

In case you want to access the test name, you could just access it through the test case like:
```java
   @Override
    public void onTestSuccess(TestCase test) {
        String testName = test.getName();
    }
```

For some more samples, please have a look at the [reporting sample](https://github.com/citrusframework/citrus-samples/tree/master/sample-reporting/java-dsl).

If you want to pass data from your test to your reporter, you could do it as you did, via the test context or you could inject the reporter into your test case to set the data required for your reporting.

*Test*
```java
@Test
public class SimpleSampleIT extends TestNGCitrusTestRunner {

    @Autowired
    ExtentReporter extentReporter;

    @CitrusTest
    public void testSuccessFirst() {
        extentReporter.setTestData("foo");
        echo("1st test successful");
    }

    @CitrusTest
    public void testSuccessSecond() {
        extentReporter.setTestData("bar");
        echo("2nd test successful");
    }
}
```

*Reporter*
```java
public class ExtentReporter extends AbstractTestReporter implements TestReporter{
    
    private String testData;

    @Override
    public void onTestSuccess(final TestCase test) {
        //Do something with testData
    }

    @Override
    public void onTestSkipped(final TestCase test) {
        //Do something with testData
    }

    @Override
    public void onTestFailure(final TestCase test, final Throwable cause) {
        //Do something with testData
    }

    @Override
    public void clearTestResults(){
        testData = "";
    }

    public void setTestData(final String testData){
        this.testData = testData;
    }
}
```

As this issue is solved, I'll close it. =)

BR,
Sven
